version: '2'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.1.0
    hostname: zookeeper.kerberos.example
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kerberos:
    image: kwart/kerberos-server
    hostname: kdc.kerberos.example
    container_name: kerberos
    volumes:
      - ./data.ldif:/mnt/data.ldif
      - ./krb5.conf:/etc/krb5.conf
    command: [ "-lp", "389", "-kp", "88", "-b", "0.0.0.0",  "/mnt/data.ldif" ]

  broker:
    image: confluentinc/cp-kafka:7.1.0
    hostname: broker.kerberos.example
    container_name: broker
    depends_on:
      - zookeeper
      - kerberos
    volumes:
      - ./kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf
      - ./kafka_server.keytab:/mnt/kafka_server.keytab
      - ./krb5.conf:/etc/krb5.conf
    environment:
      KAFKA_SASL_ENABLED_MECHANISMS: GSSAPI
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: GSSAPI
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SASL_PLAINTEXT
      KAFKA_LISTENERS: SASL_PLAINTEXT://broker.kerberos.example:9092
      KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://broker.kerberos.example:9092
      CONFIG_STORAGE_REPLICATION_FACTOR: "1"
      OFFSET_STORAGE_REPLICATION_FACTOR: "1"
      STATUS_STORAGE_REPLICATION_FACTOR: "1"
      KAFKA_SASL_KERBEROS_SERVICE_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper.kerberos.example:2181'
      ZOOKEEPER_SASL_ENABLED: "false"
      KAFKA_OPTS: '-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf -Dsun.security.krb5.debug=true -Dcom.ibm.security.jgss.debug=all -Dcom.ibm.security.krb5.Krb5Debug=all -Dsun.security.jgss.debug=true'
