version: '2'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.1.0
    hostname: zookeeper.kerberos.example
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kerberos:
    image: kwart/kerberos-server
    hostname: kdc.kerberos.example
    container_name: kerberos
    ports:
      - "389:389"
      - "88:88"
    volumes:
      - ./data.ldif:/mnt/data.ldif
    command: [ "-lp", "389", "-kp", "88", "-b", "0.0.0.0",  "/mnt/data.ldif" ]

  broker:
    image: confluentinc/cp-kafka:7.1.0
    hostname: broker.kerberos.example
    container_name: broker
    depends_on:
      - zookeeper
      - kerberos
    ports:
      - "29092:29092"
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_SASL_ENABLED_MECHANISMS: GSSAPI
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: GSSAPI
      KAFKA_SASL_KERBEROS_SERVICE_NAME: kerberos
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_PLAINTEXT_HOST:SASL_PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,SASL_PLAINTEXT://kafka1:9093,PLAINTEXT_HOST://localhost:29092,SASL_PLAINTEXT://localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LISTENER_NAME_SASL___SSL_GSSAPI_SASL_JASS_CONFIG: com.sun.security.auth.module.Krb5LoginModule required \
        useKeyTab=true \
        storeKey=true \
        keyTab="/etc/security/keytabs/kafka_server.keytab" \
        principal="kerberos/hnelson@KERBEROS.EXAMPLE";
      KAFKA_OPTS: '-Djava.security.auth.login.config='

  hazelcast:
    image: hazelcast/hazelcast:latest
    hostname: hazelcast
    container_name: hazelcast
    depends_on:
      - broker
    ports:
    - "5701:5701"
  management-center:
    image: hazelcast/management-center:latest
    hostname: management-center
    container_name: management-center
    ports:
    - "8080:8080"
    environment:
    - MC_DEFAULT_CLUSTER=dev
    - MC_DEFAULT_CLUSTER_MEMBERS=hazelcast
